# Generated by Django 4.2.2 on 2023-09-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_date_of_death_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'create or update a book'), ('can_delete_book', 'delete a book'))},
        ),
    ]
